# Generated by Django 5.0 on 2024-06-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_brand_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
